Update helpers.py
Tmp folder permission may mislead root cause showing issue with binding socket

```
Detected system: Linux
Inference engine name after selection: tinygrad
get_inference_engine called with: tinygrad
Using inference engine: TinygradDynamicShardInferenceEngine with shard downloader: HFShardDownloader
Trying to find available port host='0.0.0.0' port=61382
Unable write to file
Traceback (most recent call last):
  File "/home/user/exo/exo/helpers.py", line 62, in find_available_port
    write_used_port(port, used_ports)
  File "/home/user/exo/exo/helpers.py", line 47, in write_used_port
    with open(used_ports_file, "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/tmp/exo_used_ports'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/exo/.venv/bin/exo", line 5, in <module>
    from exo.main import run
  File "/home/user/exo/exo/main.py", line 72, in <module>
    args.node_port = find_available_port(args.node_host)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/exo/exo/helpers.py", line 66, in find_available_port
    raise RuntimeError (e)
RuntimeError: [Errno 13] Permission denied: '/tmp/exo_used_ports'
```